package main

import (
	"reflect"
	"testing"
)

func TestProductionPathClassification(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		path string
		want bool
	}{
		{path: "internal/runtime/app/runtime.go", want: true},
		{path: "extensions/vscode/src/chat/view.ts", want: true},
		{path: "internal/runtime/app/runtime_test.go", want: false},
		{path: "extensions/vscode/src/chat/view.test.ts", want: false},
		{path: "testdata/provider/server.go", want: false},
		{path: "docs/example.ts", want: false},
		{path: "extensions/vscode/dist/extension.js", want: false},
	} {
		if got := productionPath(test.path); got != test.want {
			t.Errorf("productionPath(%q) = %t, want %t", test.path, got, test.want)
		}
	}
}

func TestGeneratedAndLineCount(t *testing.T) {
	t.Parallel()
	if !generated([]byte("// Code generated by tool. DO NOT EDIT.\npackage x\n")) {
		t.Fatal("generated source was not detected")
	}
	if generated([]byte("// generated examples are editable\n")) {
		t.Fatal("ordinary source was classified as generated")
	}
	for _, test := range []struct {
		content string
		want    int
	}{
		{content: "", want: 0},
		{content: "one", want: 1},
		{content: "one\n", want: 1},
		{content: "one\ntwo", want: 2},
	} {
		if got := lineCount([]byte(test.content)); got != test.want {
			t.Errorf("lineCount(%q) = %d, want %d", test.content, got, test.want)
		}
	}
}

func TestSummarizeTracksNetAndFileLifecycle(t *testing.T) {
	t.Parallel()
	result := summarize(
		"origin/main",
		[]string{"internal/runtime"},
		map[string]int{"a.go": 10, "deleted.go": 5},
		map[string]int{"a.go": 7, "added.go": 4},
		0,
	)
	if result.BaseLines != 15 || result.HeadLines != 11 ||
		result.AddedLines != 4 || result.DeletedLines != 8 ||
		result.NetLines != -4 || result.Status != "passed" {
		t.Fatalf("unexpected report: %+v", result)
	}
}

func TestNormalizePathsDeduplicatesAndSorts(t *testing.T) {
	t.Parallel()
	got := normalizePaths([]string{
		"internal/runtime/app/",
		"internal/runtime/agent",
		"internal/runtime/app",
	})
	want := []string{"internal/runtime/agent", "internal/runtime/app"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("normalizePaths() = %v, want %v", got, want)
	}
}
