// Code generated by scripts/generate-protocol.mjs. DO NOT EDIT.
// Source: docs/protocol/runtime-protocol.schema.json

export const protocolVersion = 1 as const;

export const operationKinds = [
  "approval.decision",
  "input.reply",
  "thread.compact",
  "thread.fork",
  "turn.cancel",
  "turn.revert",
  "turn.start",
  "turn.steer"
] as const;
export type OperationKind = (typeof operationKinds)[number];

export const eventKinds = [
  "agent.integration",
  "agent.message",
  "agent.spawned",
  "agent.status",
  "approval.required",
  "approval.resolved",
  "checkpoint.created",
  "checkpoint.forked",
  "checkpoint.restored",
  "citation",
  "command.execution",
  "diagnostics.result",
  "extension.lifecycle",
  "host.command",
  "input.required",
  "input.resolved",
  "mcp.health.changed",
  "operation.rejected",
  "output.delta",
  "plan.delta",
  "reasoning.delta",
  "reasoning.signature",
  "search.result",
  "thread.compacted",
  "thread.forked",
  "tool.catalog.changed",
  "tool.output",
  "tool.result",
  "tool.start",
  "tool.state",
  "turn.canceled",
  "turn.compaction",
  "turn.completed",
  "turn.failed",
  "turn.receipt",
  "turn.reverted",
  "turn.started",
  "turn.steered",
  "turn.verification",
  "usage"
] as const;
export type EventKind = (typeof eventKinds)[number];

export type EventClass = "accounting" | "artifact" | "artifact_stream" | "audit" | "evidence" | "interaction" | "lifecycle" | "orchestration" | "stream" | "terminal" | "terminal_operation";
export type ItemOwner = "agent" | "approval" | "checkpoint" | "input" | "operation" | "thread" | "tool" | "turn";
export type Durability = "atomic" | "bounded" | "retained" | "terminal_projection" | "transient";
export type CorrelationKind = "agent" | "call" | "catalog" | "checkpoint" | "command" | "extension" | "mutation" | "operation" | "plan" | "request" | "sample" | "server" | "target_turn" | "thread" | "turn";
export interface EventTraits {
  readonly class: EventClass;
  readonly item_owner: ItemOwner;
  readonly durability: Durability;
  readonly correlation: CorrelationKind;
  readonly terminal: boolean;
}
export const eventTraits = {
  "agent.integration": {"class":"orchestration","item_owner":"agent","durability":"retained","correlation":"agent","terminal":false},
  "agent.message": {"class":"orchestration","item_owner":"agent","durability":"retained","correlation":"agent","terminal":false},
  "agent.spawned": {"class":"orchestration","item_owner":"agent","durability":"retained","correlation":"agent","terminal":false},
  "agent.status": {"class":"orchestration","item_owner":"agent","durability":"retained","correlation":"agent","terminal":false},
  "approval.required": {"class":"interaction","item_owner":"approval","durability":"retained","correlation":"request","terminal":false},
  "approval.resolved": {"class":"interaction","item_owner":"approval","durability":"retained","correlation":"request","terminal":false},
  "checkpoint.created": {"class":"artifact","item_owner":"checkpoint","durability":"retained","correlation":"checkpoint","terminal":false},
  "checkpoint.forked": {"class":"artifact","item_owner":"checkpoint","durability":"retained","correlation":"checkpoint","terminal":false},
  "checkpoint.restored": {"class":"artifact","item_owner":"checkpoint","durability":"retained","correlation":"checkpoint","terminal":false},
  "citation": {"class":"evidence","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "command.execution": {"class":"audit","item_owner":"tool","durability":"retained","correlation":"call","terminal":false},
  "diagnostics.result": {"class":"evidence","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "extension.lifecycle": {"class":"audit","item_owner":"turn","durability":"retained","correlation":"extension","terminal":false},
  "host.command": {"class":"interaction","item_owner":"turn","durability":"retained","correlation":"command","terminal":false},
  "input.required": {"class":"interaction","item_owner":"input","durability":"retained","correlation":"request","terminal":false},
  "input.resolved": {"class":"interaction","item_owner":"input","durability":"retained","correlation":"request","terminal":false},
  "mcp.health.changed": {"class":"audit","item_owner":"turn","durability":"retained","correlation":"server","terminal":false},
  "operation.rejected": {"class":"terminal_operation","item_owner":"operation","durability":"retained","correlation":"operation","terminal":false},
  "output.delta": {"class":"stream","item_owner":"turn","durability":"terminal_projection","correlation":"turn","terminal":false},
  "plan.delta": {"class":"artifact_stream","item_owner":"turn","durability":"retained","correlation":"plan","terminal":false},
  "reasoning.delta": {"class":"stream","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "reasoning.signature": {"class":"audit","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "search.result": {"class":"evidence","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "thread.compacted": {"class":"lifecycle","item_owner":"thread","durability":"retained","correlation":"thread","terminal":false},
  "thread.forked": {"class":"lifecycle","item_owner":"thread","durability":"retained","correlation":"thread","terminal":false},
  "tool.catalog.changed": {"class":"audit","item_owner":"turn","durability":"retained","correlation":"catalog","terminal":false},
  "tool.output": {"class":"stream","item_owner":"tool","durability":"bounded","correlation":"call","terminal":false},
  "tool.result": {"class":"lifecycle","item_owner":"tool","durability":"retained","correlation":"call","terminal":false},
  "tool.start": {"class":"lifecycle","item_owner":"tool","durability":"retained","correlation":"call","terminal":false},
  "tool.state": {"class":"lifecycle","item_owner":"turn","durability":"transient","correlation":"turn","terminal":false},
  "turn.canceled": {"class":"terminal","item_owner":"turn","durability":"atomic","correlation":"turn","terminal":true},
  "turn.compaction": {"class":"audit","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "turn.completed": {"class":"terminal","item_owner":"turn","durability":"atomic","correlation":"turn","terminal":true},
  "turn.failed": {"class":"terminal","item_owner":"turn","durability":"atomic","correlation":"turn","terminal":true},
  "turn.receipt": {"class":"evidence","item_owner":"turn","durability":"atomic","correlation":"turn","terminal":false},
  "turn.reverted": {"class":"lifecycle","item_owner":"turn","durability":"retained","correlation":"target_turn","terminal":false},
  "turn.started": {"class":"lifecycle","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "turn.steered": {"class":"interaction","item_owner":"turn","durability":"retained","correlation":"turn","terminal":false},
  "turn.verification": {"class":"evidence","item_owner":"turn","durability":"retained","correlation":"mutation","terminal":false},
  "usage": {"class":"accounting","item_owner":"turn","durability":"retained","correlation":"sample","terminal":false},
} as const satisfies Record<EventKind, EventTraits>;

export type OperationEnvelope = {
  readonly "created_at": string;
  readonly "id": string;
  readonly "kind": "turn.start" | "turn.cancel" | "turn.steer" | "approval.decision" | "input.reply" | "thread.compact" | "thread.fork" | "turn.revert";
  readonly "payload": Readonly<Record<string, unknown>>;
  readonly "version": number;
};

export type EventEnvelope = {
  readonly "created_at": string;
  readonly "data": Readonly<Record<string, unknown>>;
  readonly "id": string;
  readonly "item_id": string;
  readonly "kind": "turn.started" | "output.delta" | "reasoning.delta" | "reasoning.signature" | "search.result" | "citation" | "usage" | "tool.state" | "tool.start" | "tool.output" | "tool.result" | "tool.catalog.changed" | "mcp.health.changed" | "extension.lifecycle" | "diagnostics.result" | "turn.completed" | "turn.failed" | "turn.canceled" | "operation.rejected" | "turn.steered" | "approval.required" | "approval.resolved" | "input.required" | "input.resolved" | "thread.compacted" | "thread.forked" | "turn.reverted" | "checkpoint.created" | "checkpoint.restored" | "checkpoint.forked" | "turn.compaction" | "agent.spawned" | "agent.status" | "agent.message" | "agent.integration" | "plan.delta" | "command.execution" | "host.command" | "turn.receipt" | "turn.verification";
  readonly "operation_id": string;
  readonly "sequence": number;
  readonly "thread_id": string;
  readonly "turn_id": string;
  readonly "version": number;
};

export type ProtocolProblem = {
  readonly "code": string;
  readonly "details"?: {
      readonly "actual_revision"?: number;
      readonly "expected_revision"?: number;
      readonly "reason": string;
      readonly "resource_id"?: string;
      readonly "session_status"?: string;
    };
  readonly "http_status"?: number;
  readonly "message": string;
  readonly "rate_limit"?: {
      readonly "limit"?: string;
      readonly "remaining"?: string;
      readonly "reset"?: string;
      readonly "retry_after_ms"?: number;
    };
  readonly "retryable": boolean;
  readonly "version": number;
};

export type SessionProfileSnapshot = {
  readonly "capabilities": {
      readonly "model": string;
      readonly "model_capabilities": {
            readonly "availability": string;
            readonly "context_window": number;
            readonly "credential_status": string;
            readonly "default_reasoning_effort"?: string;
            readonly "display_name": string;
            readonly "image_input": boolean;
            readonly "max_output_tokens": number;
            readonly "native_search": boolean;
            readonly "parallel_tool_calls": string;
            readonly "prompt_cache": boolean;
            readonly "reasoning": boolean;
            readonly "reasoning_efforts"?: ReadonlyArray<string>;
            readonly "selection_mode": string;
            readonly "streaming": boolean;
            readonly "tool_calls": boolean;
            readonly "unavailable_reason"?: string;
            readonly "vision": boolean;
          };
      readonly "mutable_fields": ReadonlyArray<string>;
      readonly "provider": string;
    };
  readonly "profile": {
      readonly "approval_posture": string;
      readonly "enabled_tool_ids"?: ReadonlyArray<string>;
      readonly "execution_target": string;
      readonly "max_steps": number;
      readonly "mode": string;
      readonly "model": string;
      readonly "prompt_cache_revision": number;
      readonly "provider": string;
      readonly "reasoning_effort"?: string;
      readonly "revision": number;
      readonly "version": number;
    };
};

export type SessionProfilePatch = {
  readonly "approval_posture"?: string;
  readonly "enabled_tool_ids"?: ReadonlyArray<string>;
  readonly "execution_target"?: string;
  readonly "max_steps"?: number;
  readonly "mode"?: string;
  readonly "model"?: string;
  readonly "provider"?: string;
  readonly "reasoning_effort"?: string;
};

export type SessionProfileUpdate = {
  readonly "profile": {
      readonly "approval_posture": string;
      readonly "enabled_tool_ids"?: ReadonlyArray<string>;
      readonly "execution_target": string;
      readonly "max_steps": number;
      readonly "mode": string;
      readonly "model": string;
      readonly "prompt_cache_revision": number;
      readonly "provider": string;
      readonly "reasoning_effort"?: string;
      readonly "revision": number;
      readonly "version": number;
    };
  readonly "prompt_cache_reset": boolean;
  readonly "reset_reason"?: string;
};

export type ProviderCatalog = {
  readonly "providers": ReadonlyArray<{
      readonly "availability": string;
      readonly "display_name": string;
      readonly "id": string;
      readonly "reason"?: string;
      readonly "selected": boolean;
    }>;
  readonly "version": number;
};

export type ModelCatalog = {
  readonly "models": ReadonlyArray<{
      readonly "capabilities": {
            readonly "availability": string;
            readonly "context_window": number;
            readonly "credential_status": string;
            readonly "default_reasoning_effort"?: string;
            readonly "display_name": string;
            readonly "image_input": boolean;
            readonly "max_output_tokens": number;
            readonly "native_search": boolean;
            readonly "parallel_tool_calls": string;
            readonly "prompt_cache": boolean;
            readonly "reasoning": boolean;
            readonly "reasoning_efforts"?: ReadonlyArray<string>;
            readonly "selection_mode": string;
            readonly "streaming": boolean;
            readonly "tool_calls": boolean;
            readonly "unavailable_reason"?: string;
            readonly "vision": boolean;
          };
      readonly "id": string;
      readonly "provider": string;
      readonly "selected": boolean;
    }>;
  readonly "version": number;
};

export type SessionToolCatalog = {
  readonly "catalog_id": string;
  readonly "digest": string;
  readonly "generation": number;
  readonly "tools": ReadonlyArray<{
      readonly "access_mode": string;
      readonly "availability": string;
      readonly "capability": string;
      readonly "constitution_reason": string;
      readonly "constitution_state": string;
      readonly "description": string;
      readonly "enabled": boolean;
      readonly "guarded": boolean;
      readonly "id": string;
      readonly "name": string;
      readonly "policy_reason": string;
      readonly "policy_state": string;
      readonly "revision": number;
      readonly "risk_level": string;
      readonly "sandbox_requirement": string;
      readonly "source_kind": string;
      readonly "source_label": string;
      readonly "state": string;
      readonly "unavailable_reason"?: string;
    }>;
  readonly "version": number;
};

export type SessionList = {
  readonly "matches"?: ReadonlyArray<{
      readonly "kind": string;
      readonly "session_id": string;
      readonly "snippet"?: string;
      readonly "turn_id": string;
    }>;
  readonly "query"?: string;
  readonly "sessions": ReadonlyArray<{
      readonly "archived": boolean;
      readonly "changed_files": number;
      readonly "checkpoint_count": number;
      readonly "cost_known": boolean;
      readonly "cost_microunits": number;
      readonly "created_at": string;
      readonly "execution_target": string;
      readonly "isolation": string;
      readonly "latest_sequence": number;
      readonly "latest_turn_id"?: string;
      readonly "mode"?: string;
      readonly "model"?: string;
      readonly "parent_thread_id"?: string;
      readonly "pending_approvals": number;
      readonly "pending_inputs": number;
      readonly "pinned": boolean;
      readonly "provider"?: string;
      readonly "revision": number;
      readonly "session_id": string;
      readonly "status": string;
      readonly "thread_id": string;
      readonly "title": string;
      readonly "total_tokens": number;
      readonly "updated_at": string;
      readonly "version": number;
      readonly "workspace_label": string;
      readonly "workspace_root": string;
    }>;
  readonly "version": number;
};

export type SessionLifecyclePatch = {
  readonly "archived"?: boolean;
  readonly "pinned"?: boolean;
  readonly "title"?: string;
};

export type SessionLifecycleUpdate = {
  readonly "session": {
      readonly "archived": boolean;
      readonly "changed_files": number;
      readonly "checkpoint_count": number;
      readonly "cost_known": boolean;
      readonly "cost_microunits": number;
      readonly "created_at": string;
      readonly "execution_target": string;
      readonly "isolation": string;
      readonly "latest_sequence": number;
      readonly "latest_turn_id"?: string;
      readonly "mode"?: string;
      readonly "model"?: string;
      readonly "parent_thread_id"?: string;
      readonly "pending_approvals": number;
      readonly "pending_inputs": number;
      readonly "pinned": boolean;
      readonly "provider"?: string;
      readonly "revision": number;
      readonly "session_id": string;
      readonly "status": string;
      readonly "thread_id": string;
      readonly "title": string;
      readonly "total_tokens": number;
      readonly "updated_at": string;
      readonly "version": number;
      readonly "workspace_label": string;
      readonly "workspace_root": string;
    };
};

export type SessionDelete = {
  readonly "deleted_at": string;
  readonly "session_id": string;
  readonly "thread_id": string;
  readonly "version": number;
};

export type CheckpointList = {
  readonly "checkpoints": ReadonlyArray<{
      readonly "can_fork": boolean;
      readonly "can_restore": boolean;
      readonly "change_receipt"?: {
            readonly "cursor": number;
            readonly "event_id": string;
            readonly "turn_id": string;
          };
      readonly "changed_files": number;
      readonly "created_at": string;
      readonly "cursor": number;
      readonly "external_side_effects": boolean;
      readonly "id": string;
      readonly "parent_checkpoint_id"?: string;
      readonly "profile_revision": number;
      readonly "session_id": string;
      readonly "side_effect_note"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "thread_id": string;
      readonly "turn_id": string;
      readonly "version": number;
    }>;
  readonly "session_id": string;
  readonly "version": number;
};

export type CheckpointRestore = {
  readonly "checkpoint": {
      readonly "can_fork": boolean;
      readonly "can_restore": boolean;
      readonly "change_receipt"?: {
            readonly "cursor": number;
            readonly "event_id": string;
            readonly "turn_id": string;
          };
      readonly "changed_files": number;
      readonly "created_at": string;
      readonly "cursor": number;
      readonly "external_side_effects": boolean;
      readonly "id": string;
      readonly "parent_checkpoint_id"?: string;
      readonly "profile_revision": number;
      readonly "session_id": string;
      readonly "side_effect_note"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "thread_id": string;
      readonly "turn_id": string;
      readonly "version": number;
    };
  readonly "restored_cursor": number;
  readonly "side_effects_replayed": boolean;
  readonly "thread_id": string;
  readonly "version": number;
};

export type CheckpointFork = {
  readonly "checkpoint": {
      readonly "can_fork": boolean;
      readonly "can_restore": boolean;
      readonly "change_receipt"?: {
            readonly "cursor": number;
            readonly "event_id": string;
            readonly "turn_id": string;
          };
      readonly "changed_files": number;
      readonly "created_at": string;
      readonly "cursor": number;
      readonly "external_side_effects": boolean;
      readonly "id": string;
      readonly "parent_checkpoint_id"?: string;
      readonly "profile_revision": number;
      readonly "session_id": string;
      readonly "side_effect_note"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "thread_id": string;
      readonly "turn_id": string;
      readonly "version": number;
    };
  readonly "parent_thread_id": string;
  readonly "session_id": string;
  readonly "thread_id": string;
  readonly "version": number;
};

export type SessionPlan = {
  readonly "artifact"?: {
      readonly "body": string;
      readonly "can_autopilot": boolean;
      readonly "can_implement": boolean;
      readonly "created_at": string;
      readonly "cursor": number;
      readonly "id": string;
      readonly "profile_revision": number;
      readonly "session_id": string;
      readonly "status": string;
      readonly "thread_id": string;
      readonly "turn_id": string;
      readonly "version": number;
    };
  readonly "version": number;
};

export type TurnRecoveryRequest = {
  readonly "action": string;
  readonly "guidance"?: string;
  readonly "idempotency_key": string;
  readonly "session_id": string;
  readonly "source_turn_id": string;
  readonly "version": number;
};

export type PlanTransitionRequest = {
  readonly "checkpoint_id"?: string;
  readonly "destination": string;
  readonly "idempotency_key": string;
  readonly "plan_id": string;
  readonly "session_id": string;
  readonly "title"?: string;
  readonly "transition": string;
  readonly "version": number;
};

export type ApprovalDecisionPayload = {
  readonly "decision": string;
  readonly "expires_at"?: string;
  readonly "item_id": string;
  readonly "plan_id"?: string;
  readonly "replacement_arguments"?: unknown;
  readonly "request_id": string;
  readonly "scope"?: string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export type InputReplyPayload = {
  readonly "answer": string;
  readonly "item_id": string;
  readonly "request_id": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
  readonly "values"?: Readonly<Record<string, unknown>>;
};

export type ThreadCompactPayload = {
  readonly "item_id": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export type ThreadForkPayload = {
  readonly "item_id": string;
  readonly "new_thread_id": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export type TurnCancelPayload = {
  readonly "item_id": string;
  readonly "reason"?: string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export type TurnRevertPayload = {
  readonly "item_id": string;
  readonly "target_turn_id": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export type TurnStartPayload = {
  readonly "context"?: ReadonlyArray<{
      readonly "content"?: string;
      readonly "diagnostics"?: ReadonlyArray<{
            readonly "code"?: string;
            readonly "message": string;
            readonly "range": {
                    readonly "end": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                    readonly "start": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                  };
            readonly "severity": string;
            readonly "source"?: string;
          }>;
      readonly "digest": string;
      readonly "document_version": number;
      readonly "explicit": boolean;
      readonly "kind": "file" | "selection" | "symbol" | "diagnostics" | "image" | "terminal" | "git_diff";
      readonly "label"?: string;
      readonly "media_type"?: string;
      readonly "omitted_diagnostics"?: number;
      readonly "path": string;
      readonly "range"?: {
            readonly "end": {
                    readonly "character": number;
                    readonly "line": number;
                  };
            readonly "start": {
                    readonly "character": number;
                    readonly "line": number;
                  };
          };
      readonly "source"?: "composer" | "selection_command" | "code_action" | "native_picker";
      readonly "symbol"?: {
            readonly "kind": string;
            readonly "name": string;
            readonly "selection_range"?: {
                    readonly "end": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                    readonly "start": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                  };
          };
      readonly "uri": string;
    }>;
  readonly "display_prompt"?: string;
  readonly "idle"?: boolean;
  readonly "intent"?: string;
  readonly "item_id": string;
  readonly "prompt": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
  readonly "workspace_identity"?: {
      readonly "editor_uri": string;
      readonly "remote_name"?: string;
      readonly "root_id": string;
      readonly "runtime_path": string;
      readonly "version": number;
    };
};

export type TurnSteerPayload = {
  readonly "item_id": string;
  readonly "prompt": string;
  readonly "thread_id": string;
  readonly "turn_id": string;
};

export interface OperationPayloadByKind {
  readonly "approval.decision": ApprovalDecisionPayload;
  readonly "input.reply": InputReplyPayload;
  readonly "thread.compact": ThreadCompactPayload;
  readonly "thread.fork": ThreadForkPayload;
  readonly "turn.cancel": TurnCancelPayload;
  readonly "turn.revert": TurnRevertPayload;
  readonly "turn.start": TurnStartPayload;
  readonly "turn.steer": TurnSteerPayload;
}

export type AgentIntegrationData = {
  readonly "agent_id": string;
  readonly "agent_path": string;
  readonly "conflicts"?: ReadonlyArray<string>;
  readonly "detail"?: unknown;
  readonly "message"?: string;
  readonly "parent_path": string;
  readonly "paths"?: ReadonlyArray<string>;
  readonly "preview_digest": string;
  readonly "session_id": string;
  readonly "status": string;
  readonly "workspace_root": string;
};

export type AgentMessageData = {
  readonly "body": unknown;
  readonly "from": string;
  readonly "sequence": number;
  readonly "session_id": string;
  readonly "to": string;
  readonly "workspace_root": string;
};

export type AgentSpawnedData = {
  readonly "agent_id": string;
  readonly "depth": number;
  readonly "detail"?: unknown;
  readonly "parent_id"?: string;
  readonly "profile"?: string;
  readonly "role": string;
  readonly "session_id": string;
  readonly "stance"?: string;
  readonly "workspace_root": string;
  readonly "worktree"?: string;
};

export type AgentStatusData = {
  readonly "agent_id": string;
  readonly "detail"?: unknown;
  readonly "message"?: string;
  readonly "session_id": string;
  readonly "status": string;
  readonly "workspace_root": string;
};

export type ApprovalRequiredData = {
  readonly "allowed_scopes": ReadonlyArray<string>;
  readonly "arguments": unknown;
  readonly "arguments_digest": string;
  readonly "call_id": string;
  readonly "edit_plan"?: {
      readonly "diff": string;
      readonly "files": ReadonlyArray<{
            readonly "after"?: string;
            readonly "after_digest": string;
            readonly "after_exists": boolean;
            readonly "before"?: string;
            readonly "before_digest": string;
            readonly "before_exists": boolean;
            readonly "kind": string;
            readonly "path": string;
          }>;
      readonly "id": string;
    };
  readonly "expires_at": string;
  readonly "modifiable_arguments": ReadonlyArray<string>;
  readonly "network"?: {
      readonly "host": string;
      readonly "mode": string;
      readonly "protocol": string;
    };
  readonly "reason"?: string;
  readonly "replacement_allowed": boolean;
  readonly "request_id": string;
  readonly "resources": ReadonlyArray<{
      readonly "access": string;
      readonly "id"?: string;
      readonly "kind": string;
      readonly "path"?: string;
      readonly "tree"?: boolean;
    }>;
  readonly "source"?: {
      readonly "agent_id": string;
      readonly "agent_path": string;
      readonly "kind": string;
      readonly "parent_path": string;
      readonly "role": string;
      readonly "session_id": string;
      readonly "workspace_root": string;
    };
  readonly "tool": string;
};

export type ApprovalResolvedData = {
  readonly "decision": string;
  readonly "problem"?: {
      readonly "code": string;
      readonly "details"?: {
            readonly "actual_revision"?: number;
            readonly "expected_revision"?: number;
            readonly "reason": string;
            readonly "resource_id"?: string;
            readonly "session_status"?: string;
          };
      readonly "http_status"?: number;
      readonly "message": string;
      readonly "rate_limit"?: {
            readonly "limit"?: string;
            readonly "remaining"?: string;
            readonly "reset"?: string;
            readonly "retry_after_ms"?: number;
          };
      readonly "retryable": boolean;
      readonly "version": number;
    };
  readonly "request_id": string;
  readonly "source"?: {
      readonly "agent_id": string;
      readonly "agent_path": string;
      readonly "kind": string;
      readonly "parent_path": string;
      readonly "role": string;
      readonly "session_id": string;
      readonly "workspace_root": string;
    };
};

export type CheckpointCreatedData = {
  readonly "checkpoint": {
      readonly "can_fork": boolean;
      readonly "can_restore": boolean;
      readonly "change_receipt"?: {
            readonly "cursor": number;
            readonly "event_id": string;
            readonly "turn_id": string;
          };
      readonly "changed_files": number;
      readonly "created_at": string;
      readonly "cursor": number;
      readonly "external_side_effects": boolean;
      readonly "id": string;
      readonly "parent_checkpoint_id"?: string;
      readonly "profile_revision": number;
      readonly "session_id": string;
      readonly "side_effect_note"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "thread_id": string;
      readonly "turn_id": string;
      readonly "version": number;
    };
};

export type CheckpointForkedData = {
  readonly "checkpoint_id": string;
  readonly "new_thread_id": string;
  readonly "replacement_history": ReadonlyArray<{
      readonly "content": unknown;
      readonly "role": string;
      readonly "turn"?: number;
    }>;
  readonly "source_cursor": number;
  readonly "title": string;
};

export type CheckpointRestoredData = {
  readonly "checkpoint_id": string;
  readonly "replacement_history": ReadonlyArray<{
      readonly "content": unknown;
      readonly "role": string;
      readonly "turn"?: number;
    }>;
  readonly "side_effects_replayed": boolean;
  readonly "source_cursor": number;
  readonly "source_thread_id": string;
  readonly "source_turn_id": string;
};

export type CitationData = {
  readonly "end": number;
  readonly "source_id": string;
  readonly "start": number;
  readonly "title": string;
  readonly "url": string;
};

export type CommandExecutionData = {
  readonly "call_id": string;
  readonly "command": string;
  readonly "duration_ms"?: number;
  readonly "exit_code"?: number;
  readonly "handle"?: string;
  readonly "output_tail"?: string;
  readonly "session_id"?: string;
  readonly "status": string;
};

export type DiagnosticsResultData = {
  readonly "call_id": string;
  readonly "receipts": ReadonlyArray<{
      readonly "diagnostics": ReadonlyArray<{
            readonly "code"?: string;
            readonly "message": string;
            readonly "path": string;
            readonly "range": {
                    readonly "end": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                    readonly "start": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                  };
            readonly "severity": string;
            readonly "source": string;
          }>;
      readonly "error_category"?: string;
      readonly "exit_code"?: number;
      readonly "message"?: string;
      readonly "path": string;
      readonly "runner"?: string;
      readonly "status": string;
    }>;
  readonly "tool": string;
};

export type ExtensionLifecycleData = {
  readonly "action": string;
  readonly "changed_at": string;
  readonly "digest": string;
  readonly "enabled": boolean;
  readonly "extension_kind": string;
  readonly "generation": number;
  readonly "name": string;
  readonly "previous_version"?: string;
  readonly "publisher"?: string;
  readonly "source": string;
  readonly "trust": string;
  readonly "version": string;
};

export type HostCommandData = {
  readonly "args"?: ReadonlyArray<string>;
  readonly "command": string;
  readonly "output"?: string;
  readonly "status": string;
};

export type InputRequiredData = {
  readonly "call_id": string;
  readonly "expires_at": string;
  readonly "options"?: ReadonlyArray<string>;
  readonly "prompt": string;
  readonly "request_id": string;
  readonly "tool": string;
};

export type InputResolvedData = {
  readonly "answer"?: string;
  readonly "request_id": string;
};

export type McpHealthChangedData = {
  readonly "changed_at": string;
  readonly "consecutive_failures": number;
  readonly "last_error"?: string;
  readonly "previous_state"?: string;
  readonly "retry_at"?: string;
  readonly "server": string;
  readonly "state": string;
};

export type OperationRejectedData = {
  readonly "code": string;
  readonly "message": string;
};

export type OutputDeltaData = {
  readonly "text": string;
};

export type PlanDeltaData = {
  readonly "artifact_id"?: string;
  readonly "body"?: string;
  readonly "can_autopilot"?: boolean;
  readonly "can_implement"?: boolean;
  readonly "done"?: boolean;
  readonly "profile_revision"?: number;
  readonly "status"?: string;
  readonly "text"?: string;
};

export type ReasoningDeltaData = {
  readonly "text": string;
};

export type ReasoningSignatureData = {
  readonly "signature": string;
};

export type SearchResultData = {
  readonly "query": string;
  readonly "sources": ReadonlyArray<{
      readonly "id": string;
      readonly "title": string;
      readonly "url": string;
    }>;
};

export type ThreadCompactedData = {
  readonly "first_window_id"?: string;
  readonly "previous_window_id"?: string;
  readonly "replacement_history"?: ReadonlyArray<{
      readonly "content": unknown;
      readonly "role": string;
      readonly "turn"?: number;
    }>;
  readonly "summary": string;
  readonly "window_id"?: string;
  readonly "window_number"?: number;
};

export type ThreadForkedData = {
  readonly "new_thread_id": string;
  readonly "replacement_history"?: ReadonlyArray<{
      readonly "content": unknown;
      readonly "role": string;
      readonly "turn"?: number;
    }>;
  readonly "source_cursor": number;
};

export type ToolCatalogChangedData = {
  readonly "added"?: ReadonlyArray<{
      readonly "name": string;
      readonly "revision": number;
      readonly "source"?: string;
    }>;
  readonly "catalog_id": string;
  readonly "digest": string;
  readonly "generation": number;
  readonly "replaced"?: ReadonlyArray<{
      readonly "name": string;
      readonly "revision": number;
      readonly "source"?: string;
    }>;
  readonly "revoked"?: ReadonlyArray<{
      readonly "name": string;
      readonly "revision": number;
      readonly "source"?: string;
    }>;
};

export type ToolOutputData = {
  readonly "call_id": string;
  readonly "chunk": string;
  readonly "cursor": number;
  readonly "stream": string;
  readonly "tool": string;
  readonly "truncated"?: boolean;
};

export type ToolResultData = {
  readonly "call_id": string;
  readonly "changes"?: ReadonlyArray<{
      readonly "added": number;
      readonly "kind": string;
      readonly "path": string;
      readonly "removed": number;
    }>;
  readonly "completion"?: {
      readonly "accepted": boolean;
      readonly "call_id": string;
      readonly "changed_paths": ReadonlyArray<string>;
      readonly "mutation_revision": number;
      readonly "pending_actions": ReadonlyArray<string>;
      readonly "rejection"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "verification_call_ids": ReadonlyArray<string>;
    };
  readonly "is_error": boolean;
  readonly "observed_changes"?: number;
  readonly "output": string;
  readonly "recovery"?: {
      readonly "error_category": string;
      readonly "path"?: string;
      readonly "required_action": string;
      readonly "retry_original": boolean;
    };
  readonly "tool": string;
  readonly "workspace_write_scope"?: string;
};

export type ToolStartData = {
  readonly "arguments"?: unknown;
  readonly "call_id": string;
  readonly "tool": string;
};

export type ToolStateData = {
  readonly "state": string;
  readonly "text"?: string;
};

export type TurnCanceledData = {
  readonly "reason": string;
};

export type TurnCompactionData = {
  readonly "original_bytes"?: number;
  readonly "phase": string;
  readonly "removed_messages"?: number;
  readonly "removed_turns"?: ReadonlyArray<number>;
  readonly "retained_bytes"?: number;
  readonly "sections"?: ReadonlyArray<string>;
  readonly "summary": string;
  readonly "summary_truncated"?: boolean;
};

export type TurnCompletedData = {
  readonly "outcome"?: string;
  readonly "text": string;
};

export type TurnFailedData = {
  readonly "code": string;
  readonly "message": string;
  readonly "secondary_issues"?: ReadonlyArray<{
      readonly "code": string;
      readonly "message": string;
      readonly "phase": string;
    }>;
};

export type TurnReceiptData = {
  readonly "approvals_requested": number;
  readonly "budget"?: {
      readonly "cost_microunits": number;
      readonly "max_cost_microunits"?: number;
      readonly "max_tokens"?: number;
      readonly "tokens_used": number;
    };
  readonly "cached_tokens"?: number;
  readonly "catalog"?: {
      readonly "advertised"?: ReadonlyArray<string>;
      readonly "catalog_id": string;
      readonly "deferred_count": number;
      readonly "digest": string;
      readonly "generation": number;
      readonly "materialized"?: ReadonlyArray<string>;
      readonly "omitted_count": number;
    };
  readonly "changes"?: ReadonlyArray<{
      readonly "added"?: number;
      readonly "kind"?: string;
      readonly "path": string;
      readonly "removed"?: number;
      readonly "summary"?: string;
      readonly "tool": string;
    }>;
  readonly "completion"?: {
      readonly "accepted": boolean;
      readonly "call_id": string;
      readonly "changed_paths": ReadonlyArray<string>;
      readonly "mutation_revision": number;
      readonly "pending_actions": ReadonlyArray<string>;
      readonly "rejection"?: string;
      readonly "status": string;
      readonly "summary": string;
      readonly "verification_call_ids": ReadonlyArray<string>;
    };
  readonly "context_budget"?: {
      readonly "compactions": number;
      readonly "estimated_tokens"?: number;
      readonly "history_bytes": number;
      readonly "max_context_tokens"?: number;
      readonly "max_history_bytes": number;
    };
  readonly "context_sections"?: ReadonlyArray<{
      readonly "digest"?: string;
      readonly "kind": string;
      readonly "original_bytes": number;
      readonly "retained_bytes": number;
      readonly "truncated"?: boolean;
      readonly "truncation_reason"?: string;
    }>;
  readonly "context_selections"?: ReadonlyArray<{
      readonly "critical"?: boolean;
      readonly "evidence"?: ReadonlyArray<{
            readonly "kind": string;
            readonly "line"?: number;
            readonly "symbol"?: string;
            readonly "tool"?: string;
            readonly "turn": number;
          }>;
      readonly "first_turn": number;
      readonly "included": boolean;
      readonly "kind": string;
      readonly "last_turn": number;
      readonly "path": string;
      readonly "reasons": ReadonlyArray<string>;
      readonly "score": number;
      readonly "truncated"?: boolean;
      readonly "truncation_reason"?: string;
    }>;
  readonly "cost_known": boolean;
  readonly "cost_microunits": number;
  readonly "diagnostic_count": number;
  readonly "editor_context"?: ReadonlyArray<{
      readonly "diagnostic_count"?: number;
      readonly "digest": string;
      readonly "kind": "file" | "selection" | "symbol" | "diagnostics" | "image" | "terminal" | "git_diff";
      readonly "label"?: string;
      readonly "media_type"?: string;
      readonly "omitted_diagnostics"?: number;
      readonly "original_bytes": number;
      readonly "path": string;
      readonly "range"?: {
            readonly "end": {
                    readonly "character": number;
                    readonly "line": number;
                  };
            readonly "start": {
                    readonly "character": number;
                    readonly "line": number;
                  };
          };
      readonly "retained_bytes": number;
      readonly "source"?: "composer" | "selection_command" | "code_action" | "native_picker";
      readonly "symbol"?: {
            readonly "kind": string;
            readonly "name": string;
            readonly "selection_range"?: {
                    readonly "end": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                    readonly "start": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                  };
          };
      readonly "truncated"?: boolean;
    }>;
  readonly "evidence"?: {
      readonly "facts"?: ReadonlyArray<{
            readonly "kind": string;
            readonly "line"?: number;
            readonly "path": string;
            readonly "symbol"?: string;
            readonly "tool"?: string;
            readonly "turn": number;
          }>;
      readonly "omitted_facts"?: number;
      readonly "reminders"?: ReadonlyArray<string>;
      readonly "risks"?: ReadonlyArray<{
            readonly "kind": string;
            readonly "path": string;
            readonly "turn": number;
          }>;
    };
  readonly "goal": string;
  readonly "input_tokens": number;
  readonly "intent"?: string;
  readonly "latency"?: {
      readonly "approval_wait_ms": number;
      readonly "first_token_ms"?: number;
      readonly "provider_ms": number;
      readonly "tool_ms": number;
      readonly "total_ms": number;
      readonly "verify_ms": number;
    };
  readonly "latency_ms": number;
  readonly "mode"?: string;
  readonly "not_collected"?: ReadonlyArray<string>;
  readonly "outcome"?: string;
  readonly "output_tokens": number;
  readonly "plan"?: string;
  readonly "posture"?: string;
  readonly "provider_retry"?: {
      readonly "count": number;
      readonly "last_category": string;
      readonly "last_code": string;
    };
  readonly "read_paths"?: ReadonlyArray<string>;
  readonly "reasoning_tokens"?: number;
  readonly "routes"?: ReadonlyArray<{
      readonly "model": string;
      readonly "provider": string;
      readonly "purpose": string;
    }>;
  readonly "sandbox"?: string;
  readonly "secondary_issues"?: ReadonlyArray<{
      readonly "code": string;
      readonly "message": string;
      readonly "phase": string;
    }>;
  readonly "skills"?: ReadonlyArray<{
      readonly "digest": string;
      readonly "locked": boolean;
      readonly "name": string;
      readonly "plugin"?: string;
      readonly "source": string;
      readonly "version": string;
    }>;
  readonly "tools_failed"?: ReadonlyArray<string>;
  readonly "tools_succeeded"?: ReadonlyArray<string>;
  readonly "unresolved_issues"?: ReadonlyArray<string>;
  readonly "verification": {
      readonly "diagnostics": string;
      readonly "tests": string;
      readonly "verify": string;
    };
  readonly "verification_detail"?: {
      readonly "action": string;
      readonly "attempts": ReadonlyArray<{
            readonly "checks"?: ReadonlyArray<{
                    readonly "category"?: string;
                    readonly "command"?: string;
                    readonly "exit_code"?: number;
                    readonly "name": string;
                    readonly "output"?: string;
                    readonly "reason"?: string;
                    readonly "status": string;
                  }>;
            readonly "message"?: string;
            readonly "scope": string;
            readonly "status": string;
            readonly "step": number;
          }>;
      readonly "final_status": string;
      readonly "mode": string;
      readonly "repair_steps": number;
      readonly "uncovered_paths"?: ReadonlyArray<string>;
    };
  readonly "workspace"?: string;
  readonly "workspace_isolation"?: string;
  readonly "workspace_outcome"?: {
      readonly "changed"?: ReadonlyArray<string>;
      readonly "conflicts"?: ReadonlyArray<string>;
      readonly "non_file_side_effects_reverted": boolean;
      readonly "note"?: string;
      readonly "restored"?: ReadonlyArray<string>;
      readonly "status": string;
    };
};

export type TurnRevertedData = {
  readonly "conflicts": ReadonlyArray<{
      readonly "path": string;
      readonly "reason": string;
    }>;
  readonly "non_file_side_effects_note": string;
  readonly "non_file_side_effects_reverted": boolean;
  readonly "restored": ReadonlyArray<string>;
  readonly "target_turn_id": string;
};

export type TurnStartedData = {
  readonly "display_prompt"?: string;
  readonly "editor_context"?: ReadonlyArray<{
      readonly "diagnostic_count"?: number;
      readonly "digest": string;
      readonly "kind": "file" | "selection" | "symbol" | "diagnostics" | "image" | "terminal" | "git_diff";
      readonly "label"?: string;
      readonly "media_type"?: string;
      readonly "omitted_diagnostics"?: number;
      readonly "original_bytes": number;
      readonly "path": string;
      readonly "range"?: {
            readonly "end": {
                    readonly "character": number;
                    readonly "line": number;
                  };
            readonly "start": {
                    readonly "character": number;
                    readonly "line": number;
                  };
          };
      readonly "retained_bytes": number;
      readonly "source"?: "composer" | "selection_command" | "code_action" | "native_picker";
      readonly "symbol"?: {
            readonly "kind": string;
            readonly "name": string;
            readonly "selection_range"?: {
                    readonly "end": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                    readonly "start": {
                              readonly "character": number;
                              readonly "line": number;
                            };
                  };
          };
      readonly "truncated"?: boolean;
    }>;
  readonly "intent"?: string;
  readonly "mode"?: string;
  readonly "model": string;
  readonly "posture"?: string;
  readonly "prompt"?: string;
  readonly "provider": string;
  readonly "sandbox"?: string;
  readonly "workspace"?: string;
  readonly "workspace_isolation"?: string;
};

export type TurnSteeredData = {
  readonly "prompt": string;
};

export type TurnVerificationData = {
  readonly "action": string;
  readonly "checks"?: ReadonlyArray<{
      readonly "category"?: string;
      readonly "command"?: string;
      readonly "exit_code"?: number;
      readonly "name": string;
      readonly "output"?: string;
      readonly "reason"?: string;
      readonly "status": string;
    }>;
  readonly "errors"?: number;
  readonly "message"?: string;
  readonly "mode": string;
  readonly "paths"?: ReadonlyArray<string>;
  readonly "repair_steps": number;
  readonly "scope": string;
  readonly "status": string;
  readonly "uncovered_paths"?: ReadonlyArray<string>;
  readonly "warnings"?: number;
};

export type UsageData = {
  readonly "cached_tokens"?: number;
  readonly "cost_known": boolean;
  readonly "cost_microunits"?: number;
  readonly "input_tokens": number;
  readonly "model"?: string;
  readonly "output_tokens": number;
  readonly "provider"?: string;
  readonly "reasoning_tokens": number;
  readonly "sample": number;
};

export interface EventDataByKind {
  readonly "agent.integration": AgentIntegrationData;
  readonly "agent.message": AgentMessageData;
  readonly "agent.spawned": AgentSpawnedData;
  readonly "agent.status": AgentStatusData;
  readonly "approval.required": ApprovalRequiredData;
  readonly "approval.resolved": ApprovalResolvedData;
  readonly "checkpoint.created": CheckpointCreatedData;
  readonly "checkpoint.forked": CheckpointForkedData;
  readonly "checkpoint.restored": CheckpointRestoredData;
  readonly "citation": CitationData;
  readonly "command.execution": CommandExecutionData;
  readonly "diagnostics.result": DiagnosticsResultData;
  readonly "extension.lifecycle": ExtensionLifecycleData;
  readonly "host.command": HostCommandData;
  readonly "input.required": InputRequiredData;
  readonly "input.resolved": InputResolvedData;
  readonly "mcp.health.changed": McpHealthChangedData;
  readonly "operation.rejected": OperationRejectedData;
  readonly "output.delta": OutputDeltaData;
  readonly "plan.delta": PlanDeltaData;
  readonly "reasoning.delta": ReasoningDeltaData;
  readonly "reasoning.signature": ReasoningSignatureData;
  readonly "search.result": SearchResultData;
  readonly "thread.compacted": ThreadCompactedData;
  readonly "thread.forked": ThreadForkedData;
  readonly "tool.catalog.changed": ToolCatalogChangedData;
  readonly "tool.output": ToolOutputData;
  readonly "tool.result": ToolResultData;
  readonly "tool.start": ToolStartData;
  readonly "tool.state": ToolStateData;
  readonly "turn.canceled": TurnCanceledData;
  readonly "turn.compaction": TurnCompactionData;
  readonly "turn.completed": TurnCompletedData;
  readonly "turn.failed": TurnFailedData;
  readonly "turn.receipt": TurnReceiptData;
  readonly "turn.reverted": TurnRevertedData;
  readonly "turn.started": TurnStartedData;
  readonly "turn.steered": TurnSteeredData;
  readonly "turn.verification": TurnVerificationData;
  readonly "usage": UsageData;
}

export type KnownOperation = {
  readonly [Kind in OperationKind]: Omit<OperationEnvelope, "kind" | "payload"> & {
    readonly kind: Kind;
    readonly payload: OperationPayloadByKind[Kind];
  };
}[OperationKind];

export type KnownEvent = {
  readonly [Kind in EventKind]: Omit<EventEnvelope, "kind" | "data"> & {
    readonly kind: Kind;
    readonly data: EventDataByKind[Kind];
  };
}[EventKind];
