// Command webprotocolgen generates the published Web Host transport contract.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	webhost "github.com/fwtllh-png/CodeHelper/internal/host/runtimeapi/web"
)

type generated struct {
	schema     []byte
	typeScript []byte
}

func main() {
	output := flag.String(
		"output",
		"docs/protocol/web-host.schema.json",
		"generated Web Host schema output",
	)
	typeScript := flag.String(
		"typescript",
		"web/src/protocol/web-host.generated.ts",
		"generated TypeScript route contract",
	)
	check := flag.Bool("check", false, "fail if the committed output is stale")
	flag.Parse()

	content, err := generate()
	if err == nil {
		if *check {
			err = checkFile(*output, content.schema)
			if err == nil {
				err = checkFile(*typeScript, content.typeScript)
			}
		} else {
			err = writeFile(*output, content.schema)
			if err == nil {
				err = writeFile(*typeScript, content.typeScript)
			}
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "generate Web Host contract:", err)
		os.Exit(1)
	}
}

func generate() (generated, error) {
	contract := webhost.Contract()
	schema, err := json.MarshalIndent(contract, "", "  ")
	if err != nil {
		return generated{}, err
	}
	var routes []string
	for _, route := range contract.Routes {
		if route.Method == "POST" && strings.HasPrefix(route.Path, "/api/v1/") {
			routes = append(routes, strings.TrimPrefix(route.Path, "/api/v1/"))
		}
	}
	sort.Strings(routes)
	var typeScript strings.Builder
	typeScript.WriteString("// Code generated by webprotocolgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(
		&typeScript,
		"export const webProtocolVersion = %d as const;\n\n",
		contract.ProtocolVersion,
	)
	typeScript.WriteString("export const webRPCRoutes = [\n")
	for _, route := range routes {
		fmt.Fprintf(&typeScript, "  %q,\n", route)
	}
	typeScript.WriteString("] as const;\n\n")
	typeScript.WriteString(
		"export type WebRPCRoute = (typeof webRPCRoutes)[number];\n",
	)
	return generated{
		schema:     append(schema, '\n'),
		typeScript: []byte(typeScript.String()),
	}, nil
}

func checkFile(path string, expected []byte) error {
	current, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(current, expected) {
		return errors.New(path + " is stale; run make web-protocol")
	}
	return nil
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".web-host-schema-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}
