// Command eventtraitgen generates Go Event Traits from the protocol manifest.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
)

type traits struct {
	Class       string `json:"class"`
	ItemOwner   string `json:"item_owner"`
	Durability  string `json:"durability"`
	Correlation string `json:"correlation"`
	Terminal    bool   `json:"terminal"`
}

func main() {
	if len(os.Args) != 3 {
		fail(fmt.Errorf("usage: eventtraitgen <manifest> <go output>"))
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fail(err)
	}
	manifest := map[string]traits{}
	if err := json.Unmarshal(raw, &manifest); err != nil {
		fail(err)
	}
	kinds := make([]string, 0, len(manifest))
	for kind := range manifest {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)
	var output bytes.Buffer
	output.WriteString("// Code generated by eventtraitgen; DO NOT EDIT.\n\npackage protocol\n\nvar eventTraits = map[EventKind]EventTraits{\n")
	for _, kind := range kinds {
		value := manifest[kind]
		fmt.Fprintf(&output, "%q: {%q, %q, %q, %q, %t},\n",
			kind, value.Class, value.ItemOwner, value.Durability,
			value.Correlation, value.Terminal)
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(os.Args[2], formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "generate event traits:", err)
	os.Exit(1)
}
