// Code generated by observationtraitgen; DO NOT EDIT.

package observation

const (
	KindAgentClosed                Kind = "agent.closed"
	KindAgentMessageSent           Kind = "agent.message.sent"
	KindAgentResultDelivered       Kind = "agent.result.delivered"
	KindAgentSpawned               Kind = "agent.spawned"
	KindAgentTaskDelivered         Kind = "agent.task.delivered"
	KindApprovalRequested          Kind = "approval.requested"
	KindApprovalResolved           Kind = "approval.resolved"
	KindAuthorityProfileBound      Kind = "authority.profile.bound"
	KindContextCompacted           Kind = "context.compacted"
	KindContextProjected           Kind = "context.projected"
	KindContextVisibilityCommitted Kind = "context.visibility.committed"
	KindEffectFinished             Kind = "effect.finished"
	KindEffectRequested            Kind = "effect.requested"
	KindEffectRequeued             Kind = "effect.requeued"
	KindEffectResultRetained       Kind = "effect.result.retained"
	KindEffectStarted              Kind = "effect.started"
	KindEgressDecided              Kind = "egress.decided"
	KindEgressRequested            Kind = "egress.requested"
	KindExtensionOperationFinished Kind = "extension.operation.finished"
	KindExtensionOperationStarted  Kind = "extension.operation.started"
	KindExtensionSubscriberDropped Kind = "extension.subscriber.dropped"
	KindGuardDecision              Kind = "guard.decision"
	KindJournalCommitted           Kind = "journal.committed"
	KindJournalOpened              Kind = "journal.opened"
	KindJournalRolledBack          Kind = "journal.rolled_back"
	KindJournalSuspended           Kind = "journal.suspended"
	KindModelFirstOutput           Kind = "model.first_output"
	KindModelRequestFailed         Kind = "model.request.failed"
	KindModelRequestPrepared       Kind = "model.request.prepared"
	KindModelRequestSent           Kind = "model.request.sent"
	KindModelResponseCompleted     Kind = "model.response.completed"
	KindModelRetryScheduled        Kind = "model.retry.scheduled"
	KindMutationObserved           Kind = "mutation.observed"
	KindOperationAccepted          Kind = "operation.accepted"
	KindOperationRejected          Kind = "operation.rejected"
	KindProcessExited              Kind = "process.exited"
	KindProcessStarted             Kind = "process.started"
	KindProcessTeardownCompleted   Kind = "process.teardown.completed"
	KindRuntimeCrashed             Kind = "runtime.crashed"
	KindRuntimeDegraded            Kind = "runtime.degraded"
	KindRuntimeReady               Kind = "runtime.ready"
	KindRuntimeStarted             Kind = "runtime.started"
	KindRuntimeStopped             Kind = "runtime.stopped"
	KindRuntimeStopping            Kind = "runtime.stopping"
	KindSandboxAttemptStarted      Kind = "sandbox.attempt.started"
	KindSandboxDenied              Kind = "sandbox.denied"
	KindToolAdmitted               Kind = "tool.admitted"
	KindToolFinished               Kind = "tool.finished"
	KindToolProposed               Kind = "tool.proposed"
	KindToolResultModelVisible     Kind = "tool.result.model_visible"
	KindToolResultProduced         Kind = "tool.result.produced"
	KindToolRuntimeOutput          Kind = "tool.runtime.output"
	KindToolStarted                Kind = "tool.started"
	KindTurnRecovered              Kind = "turn.recovered"
	KindTurnStarted                Kind = "turn.started"
	KindTurnTerminalCommitted      Kind = "turn.terminal.committed"
	KindTurnTerminalPrepared       Kind = "turn.terminal.prepared"
	KindTurnTransitionCommitted    Kind = "turn.transition.committed"
	KindVerificationFinished       Kind = "verification.finished"
	KindVerificationStarted        Kind = "verification.started"
	KindWorkflowNodeTransitioned   Kind = "workflow.node.transitioned"
)

var observationKinds = []Kind{
	KindAgentClosed,
	KindAgentMessageSent,
	KindAgentResultDelivered,
	KindAgentSpawned,
	KindAgentTaskDelivered,
	KindApprovalRequested,
	KindApprovalResolved,
	KindAuthorityProfileBound,
	KindContextCompacted,
	KindContextProjected,
	KindContextVisibilityCommitted,
	KindEffectFinished,
	KindEffectRequested,
	KindEffectRequeued,
	KindEffectResultRetained,
	KindEffectStarted,
	KindEgressDecided,
	KindEgressRequested,
	KindExtensionOperationFinished,
	KindExtensionOperationStarted,
	KindExtensionSubscriberDropped,
	KindGuardDecision,
	KindJournalCommitted,
	KindJournalOpened,
	KindJournalRolledBack,
	KindJournalSuspended,
	KindModelFirstOutput,
	KindModelRequestFailed,
	KindModelRequestPrepared,
	KindModelRequestSent,
	KindModelResponseCompleted,
	KindModelRetryScheduled,
	KindMutationObserved,
	KindOperationAccepted,
	KindOperationRejected,
	KindProcessExited,
	KindProcessStarted,
	KindProcessTeardownCompleted,
	KindRuntimeCrashed,
	KindRuntimeDegraded,
	KindRuntimeReady,
	KindRuntimeStarted,
	KindRuntimeStopped,
	KindRuntimeStopping,
	KindSandboxAttemptStarted,
	KindSandboxDenied,
	KindToolAdmitted,
	KindToolFinished,
	KindToolProposed,
	KindToolResultModelVisible,
	KindToolResultProduced,
	KindToolRuntimeOutput,
	KindToolStarted,
	KindTurnRecovered,
	KindTurnStarted,
	KindTurnTerminalCommitted,
	KindTurnTerminalPrepared,
	KindTurnTransitionCommitted,
	KindVerificationFinished,
	KindVerificationStarted,
	KindWorkflowNodeTransitioned,
}

var observationTraits = map[Kind]Traits{
	KindAgentClosed:                {Owner: "orchestration", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "agent"}, OTEL: "span_end", Priority: "normal"},
	KindAgentMessageSent:           {Owner: "orchestration", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "agent"}, OTEL: "event", Priority: "normal"},
	KindAgentResultDelivered:       {Owner: "orchestration", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "agent"}, OTEL: "event", Priority: "normal"},
	KindAgentSpawned:               {Owner: "orchestration", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "agent"}, OTEL: "span_start", Priority: "normal"},
	KindAgentTaskDelivered:         {Owner: "orchestration", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "agent"}, OTEL: "event", Priority: "normal"},
	KindApprovalRequested:          {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn", "call"}, OTEL: "span_start", Priority: "critical"},
	KindApprovalResolved:           {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn", "call"}, OTEL: "span_end", Priority: "normal"},
	KindAuthorityProfileBound:      {Owner: "security_runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "call", "tool_attempt"}, OTEL: "event", Priority: "critical"},
	KindContextCompacted:           {Owner: "context_ledger", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn"}, OTEL: "event", Priority: "normal"},
	KindContextProjected:           {Owner: "context_ledger", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "event", Priority: "normal"},
	KindContextVisibilityCommitted: {Owner: "context_ledger", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "event", Priority: "critical"},
	KindEffectFinished:             {Owner: "effect_dispatcher", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "effect"}, OTEL: "span_end", Priority: "critical"},
	KindEffectRequested:            {Owner: "effect_dispatcher", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "effect"}, OTEL: "event", Priority: "critical"},
	KindEffectRequeued:             {Owner: "effect_dispatcher", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "effect"}, OTEL: "event", Priority: "critical"},
	KindEffectResultRetained:       {Owner: "effect_dispatcher", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "effect"}, OTEL: "event", Priority: "critical"},
	KindEffectStarted:              {Owner: "effect_dispatcher", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "effect"}, OTEL: "span_start", Priority: "critical"},
	KindEgressDecided:              {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "call", "tool_attempt"}, OTEL: "span_end", Priority: "critical"},
	KindEgressRequested:            {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "call", "tool_attempt"}, OTEL: "span_start", Priority: "critical"},
	KindExtensionOperationFinished: {Owner: "extension_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "extension"}, OTEL: "span_end", Priority: "normal"},
	KindExtensionOperationStarted:  {Owner: "extension_runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "extension"}, OTEL: "span_start", Priority: "normal"},
	KindExtensionSubscriberDropped: {Owner: "extension_runtime", Durability: "retained", Payload: "forbidden", Retention: "diagnostic", Correlations: []string{"runtime"}, OTEL: "metric", Priority: "critical"},
	KindGuardDecision:              {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "call"}, OTEL: "event", Priority: "critical"},
	KindJournalCommitted:           {Owner: "workspace_journal", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn"}, OTEL: "span_end", Priority: "critical"},
	KindJournalOpened:              {Owner: "workspace_journal", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "span_start", Priority: "critical"},
	KindJournalRolledBack:          {Owner: "workspace_journal", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn"}, OTEL: "span_end", Priority: "critical"},
	KindJournalSuspended:           {Owner: "workspace_journal", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "event", Priority: "critical"},
	KindModelFirstOutput:           {Owner: "provider_adapter", Durability: "retained", Payload: "forbidden", Retention: "diagnostic", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "event", Priority: "normal"},
	KindModelRequestFailed:         {Owner: "provider_adapter", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "span_end", Priority: "normal"},
	KindModelRequestPrepared:       {Owner: "provider_adapter", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "event", Priority: "normal"},
	KindModelRequestSent:           {Owner: "provider_adapter", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "span_start", Priority: "critical"},
	KindModelResponseCompleted:     {Owner: "provider_adapter", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "span_end", Priority: "normal"},
	KindModelRetryScheduled:        {Owner: "provider_adapter", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime", "turn", "sample"}, OTEL: "event", Priority: "critical"},
	KindMutationObserved:           {Owner: "workspace_journal", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn"}, OTEL: "event", Priority: "critical"},
	KindOperationAccepted:          {Owner: "operation", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "operation"}, OTEL: "span_start", Priority: "critical"},
	KindOperationRejected:          {Owner: "operation", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "operation"}, OTEL: "span_end", Priority: "critical"},
	KindProcessExited:              {Owner: "process_runtime", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime"}, OTEL: "span_end", Priority: "critical"},
	KindProcessStarted:             {Owner: "process_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime"}, OTEL: "span_start", Priority: "critical"},
	KindProcessTeardownCompleted:   {Owner: "process_runtime", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime"}, OTEL: "event", Priority: "critical"},
	KindRuntimeCrashed:             {Owner: "runtime", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime"}, OTEL: "span_end", Priority: "critical"},
	KindRuntimeDegraded:            {Owner: "runtime", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime"}, OTEL: "event", Priority: "critical"},
	KindRuntimeReady:               {Owner: "runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime"}, OTEL: "event", Priority: "normal"},
	KindRuntimeStarted:             {Owner: "runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime"}, OTEL: "span_start", Priority: "critical"},
	KindRuntimeStopped:             {Owner: "runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime"}, OTEL: "span_end", Priority: "critical"},
	KindRuntimeStopping:            {Owner: "runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime"}, OTEL: "event", Priority: "normal"},
	KindSandboxAttemptStarted:      {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "call", "tool_attempt"}, OTEL: "span_start", Priority: "critical"},
	KindSandboxDenied:              {Owner: "security_runtime", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "call", "tool_attempt"}, OTEL: "span_end", Priority: "critical"},
	KindToolAdmitted:               {Owner: "tool_runtime", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "call"}, OTEL: "event", Priority: "normal"},
	KindToolFinished:               {Owner: "tool_runtime", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime", "turn", "call"}, OTEL: "span_end", Priority: "normal"},
	KindToolProposed:               {Owner: "tool_runtime", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "call"}, OTEL: "event", Priority: "normal"},
	KindToolResultModelVisible:     {Owner: "context_ledger", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "call", "sample"}, OTEL: "event", Priority: "critical"},
	KindToolResultProduced:         {Owner: "tool_runtime", Durability: "retained", Payload: "optional_sensitive", Retention: "sensitive", Correlations: []string{"runtime", "turn", "call"}, OTEL: "event", Priority: "critical"},
	KindToolRuntimeOutput:          {Owner: "tool_runtime", Durability: "bounded", Payload: "optional_sensitive", Retention: "ephemeral", Correlations: []string{"runtime", "turn", "call"}, OTEL: "event", Priority: "bulk"},
	KindToolStarted:                {Owner: "tool_runtime", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "turn", "call"}, OTEL: "span_start", Priority: "critical"},
	KindTurnRecovered:              {Owner: "turn_kernel", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "event", Priority: "critical"},
	KindTurnStarted:                {Owner: "turn_kernel", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "span_start", Priority: "critical"},
	KindTurnTerminalCommitted:      {Owner: "turn_kernel", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "span_end", Priority: "normal"},
	KindTurnTerminalPrepared:       {Owner: "turn_kernel", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "event", Priority: "critical"},
	KindTurnTransitionCommitted:    {Owner: "turn_kernel", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "turn", "fact"}, OTEL: "event", Priority: "normal"},
	KindVerificationFinished:       {Owner: "verification", Durability: "retained", Payload: "optional", Retention: "diagnostic", Correlations: []string{"runtime", "turn"}, OTEL: "span_end", Priority: "normal"},
	KindVerificationStarted:        {Owner: "verification", Durability: "retained", Payload: "forbidden", Retention: "audit", Correlations: []string{"runtime", "turn"}, OTEL: "span_start", Priority: "critical"},
	KindWorkflowNodeTransitioned:   {Owner: "orchestration", Durability: "retained", Payload: "optional", Retention: "audit", Correlations: []string{"runtime", "run", "node"}, OTEL: "event", Priority: "critical"},
}
