package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/fwtllh-png/CodeHelper/internal/runtime/app/wire"
	"github.com/fwtllh-png/CodeHelper/internal/security/constitution"
	"github.com/spf13/cobra"
)

func newInitCommand(stdout, stderr io.Writer, setCode func(int)) *cobra.Command {
	cmd := &cobra.Command{
		Use: "init", Short: "Create a minimal CodeHelper workspace config and data dirs",
		Run: func(cmd *cobra.Command, args []string) {
			runWorkspaceBootstrap(cmd, stdout, stderr, setCode, false)
		},
	}
	cmd.Flags().String("workspace", ".", "workspace root")
	cmd.Flags().String("config", "", "config path (default: WORKSPACE/codehelper.toml)")
	cmd.Flags().String("data-dir", "", "state directory (default: WORKSPACE/.codehelper)")
	cmd.Flags().Bool("force", false, "overwrite existing config")
	return cmd
}

func newSetupCommand(stdout, stderr io.Writer, setCode func(int)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "setup",
		Short: "Initialize workspace plus fleet/lanes dirs and sandbox check",
		Run: func(cmd *cobra.Command, args []string) {
			runWorkspaceBootstrap(cmd, stdout, stderr, setCode, true)
		},
	}
	cmd.Flags().String("workspace", ".", "workspace root")
	cmd.Flags().String("config", "", "config path (default: WORKSPACE/codehelper.toml)")
	cmd.Flags().String("data-dir", "", "state directory (default: WORKSPACE/.codehelper)")
	cmd.Flags().Bool("force", false, "overwrite existing config")
	cmd.Flags().Bool("json", false, "emit JSON")
	return cmd
}

func runWorkspaceBootstrap(
	cmd *cobra.Command, stdout, stderr io.Writer, setCode func(int), fullSetup bool,
) {
	workspace, _ := cmd.Flags().GetString("workspace")
	configPath, _ := cmd.Flags().GetString("config")
	dataDir, _ := cmd.Flags().GetString("data-dir")
	force, _ := cmd.Flags().GetBool("force")
	asJSON := false
	if fullSetup {
		asJSON, _ = cmd.Flags().GetBool("json")
	}
	if workspace == "" {
		workspace = "."
	}
	if configPath == "" {
		configPath = filepath.Join(workspace, "codehelper.toml")
	}
	if dataDir == "" {
		dataDir = filepath.Join(workspace, ".codehelper")
	}
	if err := os.MkdirAll(workspace, 0o700); err != nil {
		_, _ = fmt.Fprintf(stderr, "codehelper: init: %v\n", err)
		setCode(1)
		return
	}
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		_, _ = fmt.Fprintf(stderr, "codehelper: init: %v\n", err)
		setCode(1)
		return
	}
	if _, err := os.Stat(configPath); err == nil && !force {
		_, _ = fmt.Fprintf(stderr, "codehelper: init: %s exists (use --force)\n", configPath)
		setCode(1)
		return
	}
	body := fmt.Sprintf("# Generated by codehelper init\n[execution]\nworkspace = %q\nmode = \"act\"\n\n[state]\ndata_dir = %q\n",
		workspace, dataDir)
	if err := os.MkdirAll(filepath.Dir(configPath), 0o700); err != nil {
		_, _ = fmt.Fprintf(stderr, "codehelper: init: %v\n", err)
		setCode(1)
		return
	}
	if err := os.WriteFile(configPath, []byte(body), 0o600); err != nil {
		_, _ = fmt.Fprintf(stderr, "codehelper: init: %v\n", err)
		setCode(1)
		return
	}
	constitutionPath := filepath.Join(dataDir, constitution.FileName)
	if err := constitution.WriteTemplate(constitutionPath, force); err != nil {
		_, _ = fmt.Fprintf(stderr, "codehelper: init constitution: %v\n", err)
		setCode(1)
		return
	}
	created := []string{configPath, dataDir, constitutionPath}
	sandboxReport := wire.CheckSandbox()
	constitutionStatus, _ := constitution.Load(workspace, "")
	if fullSetup {
		for _, sub := range []string{"fleet", "lanes", "plugins", "skills"} {
			path := filepath.Join(dataDir, sub)
			if err := os.MkdirAll(path, 0o700); err != nil {
				_, _ = fmt.Fprintf(stderr, "codehelper: setup: %v\n", err)
				setCode(1)
				return
			}
			created = append(created, path)
		}
		if asJSON {
			_ = json.NewEncoder(stdout).Encode(map[string]any{
				"ok": true, "config": configPath, "data_dir": dataDir,
				"created": created, "sandbox": sandboxReport,
				"constitution": constitutionStatus.Status,
			})
		} else {
			_, _ = fmt.Fprintf(stdout, "setup config=%s data_dir=%s dirs=%d sandbox_ok=%v constitution_rules=%d\n",
				configPath, dataDir, len(created), sandboxReport.OK, constitutionStatus.Status.RuleCount)
		}
		if !sandboxReport.OK {
			setCode(1)
			return
		}
		setCode(0)
		return
	}
	_, _ = fmt.Fprintf(stdout, "initialized config=%s data_dir=%s constitution=%s\n",
		configPath, dataDir, constitutionPath)
	setCode(0)
}
