// Code generated by scripts/generate-compatibility.mjs. DO NOT EDIT.
// Source: internal/compatibility/compatibility.json

export const compatibility = {
  "schema_version": 1,
  "extension_version": "0.0.1",
  "binary_version_range": ">=0.0.1 <0.1.0",
  "acp_protocol": {
    "min": 1,
    "max": 2
  },
  "operation_schema_version": 1,
  "required_methods": [
    "session/new",
    "session/load",
    "session/submit",
    "session/replay",
    "session/history",
    "session/list",
    "session/status",
    "session/lifecycle/update",
    "session/delete",
    "session/merge",
    "session/rename",
    "session/profile/get",
    "session/profile/update",
    "session/tool/catalog",
    "thread/list",
    "thread/get",
    "task/list",
    "agent/list",
    "usage/query",
    "shutdown"
  ],
  "required_features": [
    "editor_context_v2",
    "session_profile_v1",
    "session_lifecycle_v1",
    "unified_tool_catalog_v1",
    "workspace_identity_v1"
  ],
  "targets": [
    {
      "os": "linux",
      "arch": "amd64",
      "vscode_target": "linux-x64"
    },
    {
      "os": "linux",
      "arch": "arm64",
      "vscode_target": "linux-arm64"
    },
    {
      "os": "darwin",
      "arch": "amd64",
      "vscode_target": "darwin-x64"
    },
    {
      "os": "darwin",
      "arch": "arm64",
      "vscode_target": "darwin-arm64"
    },
    {
      "os": "windows",
      "arch": "amd64",
      "vscode_target": "win32-x64"
    }
  ],
  "channels": [
    "marketplace",
    "open-vsx",
    "enterprise",
    "offline"
  ]
} as const;
